import type { Metadata } from 'next';
import './globals.scss';
import 'public/fonts.scss';
import { Providers } from './Redux/provider';
import { v1 } from 'uuid';
import Header from './common/components/Header/Header';
import { Suspense } from 'react';
import Loading from './common/components/Loading/Loading';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body key={v1()}>
                <Header />
                <Providers>
                    <Suspense fallback={<Loading></Loading>}>{children}</Suspense>
                </Providers>
            </body>
        </html>
    );
}
